# Generated by Django 3.1.3 on 2020-11-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dualtext_api', '0002_auto_20201116_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='project_allowed', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
