# Generated by Django 3.1.3 on 2020-11-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0005_corpus_allowed_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('key', models.CharField(max_length=255)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dualtext_api.corpus')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.BinaryField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dualtext_api.document')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dualtext_api.feature')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
