# Generated by Django 3.1.3 on 2020-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0006_feature_featurevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='documents',
            field=models.ManyToManyField(blank=True, to='dualtext_api.Document'),
        ),
    ]
