# Generated by Django 3.1.3 on 2020-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0007_auto_20201207_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='key_code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
