# Generated by Django 3.1.3 on 2020-12-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0009_auto_20201207_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.JSONField(),
        ),
    ]
