# Generated by Django 3.1.3 on 2021-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0013_auto_20210104_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotation_document_duplicates',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='corpus',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_corpus_name'),
        ),
    ]
