# Generated by Django 3.1.3 on 2021-01-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0014_auto_20210104_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='is_reviewed',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_annotated',
            new_name='is_finished',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotator_labels',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='reviewer_labels',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='annotation',
            name='action',
            field=models.CharField(blank=True, choices=[('annotate', 'annotate'), ('review', 'review'), ('duplicate', 'duplicate')], default='annotate', max_length=10),
        ),
        migrations.AddField(
            model_name='annotation',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dualtext_api.annotation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(blank=True, to='dualtext_api.Label'),
        ),
        migrations.AddField(
            model_name='task',
            name='action',
            field=models.CharField(blank=True, choices=[('annotate', 'annotate'), ('review', 'review'), ('duplicate', 'duplicate')], default='annotate', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='copied_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dualtext_api.task'),
        ),
    ]
