# Generated by Django 3.1.3 on 2021-01-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0016_project_use_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotation_mode',
            field=models.CharField(blank=True, choices=[('dualtext', 'dualtext'), ('classification', 'classification')], default='dualtext', max_length=15),
        ),
    ]
