# Generated by Django 3.1.3 on 2021-01-16 14:56

from django.db import migrations, models
import dualtext_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0017_project_annotation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='key_code',
            field=models.CharField(max_length=1, null=True, validators=[dualtext_api.validators.validate_alphabetic]),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('key_code', 'project'), name='unique_key_code_in_project'),
        ),
    ]
