# Generated by Django 3.1.3 on 2021-04-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0020_lap_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dualtext_api.task')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dualtext_api.annotationgroup'),
        ),
    ]
