# Generated by Django 3.1.3 on 2021-04-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0021_auto_20210409_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotation_mode',
            field=models.CharField(blank=True, choices=[('dualtext', 'dualtext'), ('classification', 'classification'), ('grouped', 'grouped')], default='dualtext', max_length=15),
        ),
    ]
