# Generated by Django 3.1.3 on 2021-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0022_auto_20210411_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='n_documents',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
