# Generated by Django 3.1.3 on 2021-04-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0023_project_n_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='n_documents',
            new_name='max_documents',
        ),
    ]
