# Generated by Django 4.0.1 on 2022-01-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dualtext_api', '0024_auto_20210416_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='%(class)s_allowed', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='annotator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_annotator', to=settings.AUTH_USER_MODEL),
        ),
    ]
