# Generated by Django 4.0.1 on 2022-02-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0025_alter_project_allowed_groups_alter_project_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurevalue',
            name='document',
        ),
        migrations.RemoveField(
            model_name='featurevalue',
            name='feature',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='FeatureValue',
        ),
    ]
