# Generated by Django 4.0.1 on 2022-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0026_remove_featurevalue_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='corpus_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
