# Generated by Django 4.0.1 on 2022-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualtext_api', '0027_document_document_meta_alter_corpus_corpus_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
